  let g:coc_global_extensions = [
    \ 'coc-snippets',
    \ 'coc-actions',
    \ 'coc-emmet',
    \ 'coc-marketplace',
    \ 'coc-tasks',
    \ 'coc-css',
    \ 'coc-java',
    \ 'coc-yaml',
    \ 'coc-python',
    \ 'coc-vimlsp',
    \ 'coc-yank',
    \ 'coc-json',
    \ 'coc-vimtex',
    \ ]
