#! /bin/sh

feh --no fehbg --bg-fill "$HOME/.config/bspwm/wallpaper"


bspc monitor -d I II III IV V VI VII VIII IX X
pulseaudio --start &
picom --experimental-backends &
sxhkd &
xrdb ~/.Xresources &
udiskie -2 &

$HOME/.config/polybar/launch.sh &
$HOME/.config/redshift/autostart.sh &
$HOME/scripts/spotify/launchlistener.sh

g="$(bspc config window_gap)"
[[ "$g" -gt 0 ]] && for p in top bottom left right; do
    bspc config "${p}_padding" "-${g}"
done


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a vlc desktop='^9'

