#! /bin/sh

feh --no fehbg --bg-fill "$HOME/.config/bspwm/wallpaper"


xrdb ~/.Xresources &
nm-applet &
pulseaudio -k
pulseaudio --start &
picom &
sxhkd &
killall "dunst"
dunst &
xrdb ~/.Xresources &
udiskie -2 &

$HOME/.config/polybar/launch.sh &
$HOME/.config/redshift/autostart.sh &
$HOME/scripts/spotify/launchlistener.sh &

bspc monitor -d I II III IV V VI VII VIII IX X
g="$(bspc config window_gap)"
[[ "$g" -gt 0 ]] && for p in top bottom left right; do
    bspc config "${p}_padding" "-${g}"
done


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a spotify desktop='^10'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a vlc desktop='^9'
bspc rule -a Zathura state=tiled


copyq &
