#! /bin/sh

~/.fehbg

(ps x | grep bspswallow | grep -v grep) || $HOME/.local/bin/bspswallow &
nm-applet &
i3-battery-popup -n &
picom -b &
flameshot &
sxhkd &
killall "dunst"
dunst &
xrdb ~/.Xresources &
copyq &
udiskie -2 &

$HOME/.config/polybar/launch.sh &
$HOME/.config/redshift/autostart.sh &
$HOME/scripts/spotify/launchlistener.sh &

bspc monitor -d I II III IV V VI VII VIII IX X
g="$(bspc config window_gap)"
[[ "$g" -gt 0 ]] && for p in top bottom left right; do
    bspc config "${p}_padding" "-${g}"
done

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Spotify desktop='^10' 
bspc rule -a Kupfer.py focus=on
bspc rule -a discord desktop='^7' follow=off  
bspc rule -a Screenkey manage=off
bspc rule -a vlc desktop='^9'
bspc rule -a Zathura state=tiled


